#!/usr/bin/expect -f

set timeout $env(VPNTIMEOUT)

spawn /root/forticlientsslvpn/64bit/forticlientsslvpn_cli --server $env(VPNADDR) --vpnuser $env(VPNUSER)

# Send command
expect -exact "Password for VPN:"
send -- "$env(VPNPASS)\n"

expect -exact "STATUS::Connecting..."

# In case of invalid certificate
expect -exact "Would you like to connect to this server? (Y/N)" {
  send -- "Y\n"
}

# In case of invalid certificate
set docker $spawn_id
expect "An email message containing a Token Code will be sent to*"
spawn -noecho python2.7 /imap.py $env(MAILUSER) $env(MAILPASSWORD) $env(MAILSERVER)
expect EOF 
send -i $docker $expect_out(buffer)

# Expect tunnel to actually start
expect -i $docker {
  "STATUS::Tunnel running" {
  } timeout {
    send_user -- "Failed to bring tunnel up after $env(VPNTIMEOUT)s\n"
    exit 1
  }
}

# Expect tunnel to stop but not exit
set timeout -1
expect -i $docker {
  "STATUS::Tunnel closed" {
    exit 1
  }
  eof {
    exit
  }
}
