name: Docker Image CI

on:
  push:
    branches: [ master ] 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/jamescoverdale/forticlient-forwarder:latest
    - name : Push Container
      run: docker push ghcr.io/jamescoverdale/forticlient-forwarder:latest
